services:

  ftp-to-web-static-hosting:
    
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: ftp-to-web-static-hosting
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    env_file:
      - dev.env